CREATE TABLE "fact_hires" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hired_at_id" int NOT NULL,
  "department_id" int NOT NULL,
  "job_id" int NOT NULL,
  "total_hires" int NOT NULL
);

CREATE TABLE "dim_date" (
  "date_id" int PRIMARY KEY,
  "date" date NOT NULL,
  "year" int NOT NULL,
  "quarter" int NOT NULL,
  "month" int NOT NULL
);

CREATE TABLE "dim_department" (
  "department_id" int PRIMARY KEY,
  "department_name" varchar NOT NULL
);

CREATE TABLE "dim_job" (
  "job_id" int PRIMARY KEY,
  "job_name" varchar NOT NULL
);
