CREATE TABLE "hired_employees" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "full_name" varchar NOT NULL,
  "hired_at" timestamp NOT NULL,
  "department_id" int NOT NULL,
  "job_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "departments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "jobs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "hired_employees" ADD CONSTRAINT "fk_hired_employees_department" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "hired_employees" ADD CONSTRAINT "fk_hired_employees_job" FOREIGN KEY ("job_id") REFERENCES "jobs" ("id");
